// This file is automatically generated by Cargo Parcel. Do not edit it manually.

// Page imports
import * as P1 from "../pages/page.tsx";
import * as P0 from "../pages/!404/page.tsx";

// Layout imports
import * as L0 from "../pages/layout.tsx";



export default {
  "/": {
    page: P1,
    layouts: [L0],
    middleware: []
  },
  "/!404": {
    page: P0,
    layouts: [L0],
    middleware: []
  },
};
